import pandas as pd
df=pd.read_csv("mini_project/student.csv")

print(df)
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df.isnull())
print(df.isnull().sum())
print(df.duplicated())
print(df.duplicated().sum())
df = df.drop_duplicates()
print (df.head())
print(df.tail())
print(df.fillna(0))
print(df.dropna())
print(df["Marks"]>80)
print(df[df["Department"].isin(["CSE", "ME"])])
print(df.sort_values("Marks", ascending=False))
print(df.sort_values("Marks"))
print(df.groupby("Department")["Marks"].mean())
print(df.groupby("Department")["Marks"].sum())
print(df.groupby("Department")["Marks"].max())
print(df.groupby("Department")["Marks"].min())
print(df.groupby("Department")["Marks"].count())
print(df["Department"].value_counts())
result = pd.concat([students1, students2])
print(result)
result = pd.merge(employee, salary, on="EmpID")
print(result)
df["Marks"] = df["Marks"].apply(lambda x: x + 5)
print(df)